"use client";
import { ArrowRight, CircleDollarSign, MessageCircle } from "lucide-react";
import { useMemo, useState } from "react";
const whatsapp = process.env.NEXT_PUBLIC_WHATSAPP || "5527988493278";
export function Simulator(){
 const [bike,setBike]=useState("Ainda não sei"); const [budget,setBudget]=useState("Até R$ 500/mês"); const [entry,setEntry]=useState("Sem entrada definida");
 const url=useMemo(()=>`https://wa.me/${whatsapp}?text=${encodeURIComponent(`Olá Miguel! Quero fazer uma simulação. Moto: ${bike}. Orçamento mensal: ${budget}. Entrada: ${entry}.`)}`,[bike,budget,entry]);
 return <section className="simulator section"><div className="container sim-grid"><div><div className="eyebrow dark"><span/> SIMULAÇÃO RÁPIDA</div><h2>Vamos encontrar um caminho para sua Honda.</h2><p>Não é uma proposta de crédito. É um ponto de partida para você conversar com Miguel sobre as opções disponíveis.</p><div className="sim-points"><span><CircleDollarSign/> Sem compromisso</span><span><MessageCircle/> Atendimento direto</span></div></div><div className="sim-card"><label>Moto de interesse<select value={bike} onChange={e=>setBike(e.target.value)}><option>Ainda não sei</option><option>CG160 Start</option><option>CG160 Fan</option><option>CG160 Titan</option><option>NXR160 Bros</option><option>PCX</option><option>CB300F Twister</option><option>Outra Honda</option></select></label><label>Quanto pretende investir por mês?<select value={budget} onChange={e=>setBudget(e.target.value)}><option>Até R$ 500/mês</option><option>R$ 500 a R$ 800/mês</option><option>R$ 800 a R$ 1.200/mês</option><option>Acima de R$ 1.200/mês</option><option>Ainda não sei</option></select></label><label>Entrada disponível<select value={entry} onChange={e=>setEntry(e.target.value)}><option>Sem entrada definida</option><option>Até R$ 3 mil</option><option>R$ 3 mil a R$ 8 mil</option><option>Acima de R$ 8 mil</option></select></label><a className="button button-red sim-button" href={url} target="_blank" rel="noreferrer">Continuar no WhatsApp <ArrowRight size={18}/></a></div></div></section>;
}
